version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: server_admin_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: server_admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontend:
    build:
      context: .
    container_name: server_admin_frontend
    network_mode: "host"
    restart: unless-stopped

  gitea:
    image: gitea/gitea:latest
    container_name: server_admin_gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - /mnt/swarm_storage/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3030:3000"
      - "222:22"

  tunnel:
    build: ./tunnel
    container_name: server_admin_tunnel
    network_mode: "host"
    restart: always
    volumes:
      - /home/nissi/.ssh:/root/.ssh:ro

volumes:
  postgres_data:
