version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: server_admin_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: server_admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  backend:
    image: my-backend-image
    volumes:
      - /:/hostfs:ro
    pid: "host"
    privileged: true
    restart: unless-stopped

  gitea:
    image: gitea/gitea:latest
    container_name: server_admin_gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=server_admin
      - GITEA__database__USER=admin
      - GITEA__database__PASSWD=adminpassword
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - /mnt/swarm_storage/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3030:3000"
      - "222:22"

volumes:
  postgres_data:
